### ISSUE TITLE
Using an encoder with FirehoseAppender

### ISSUE THREAD

**Issue by umav-123** [guardian/kinesis-logback-appender#10]
Hi,
I want to log the messages using a custom encoder pattern like https://github.com/logstash/logstash-logback-encoder that produces a JSON output.
However the Kinesis appender doesnt seem to support adding an encoder tag like this ( it needs a 'layout' tag to specify pattern). Can you please specify how I can change the encoder class & get a JSON format log

	<appender name="KINESIS"
		class="com.hpi.codesigning.logback.appender.kinesis.FirehoseAppender">
		<bufferSize>1000</bufferSize>
		<threadCount>20</threadCount>
		<endpoint>kinesis.us-west-2.amazonaws.com</endpoint>
		<maxRetries>3</maxRetries>
		<shutdownTimeout>30</shutdownTimeout>
		<streamName>hpss-applogs-dev</streamName>
		<encoding>UTF-8</encoding>
		<region>us-west-2</region>
		<encoder class="net.logstash.logback.encoder.LogstashEncoder"/>
	</appender>

**Comment by sebastiankirsch** [comment]
Simply use
    
`<layout class="net.logstash.logback.layout.LogstashLayout"> ... </layout>`

instead.

**Comment by umav-123** [comment]
Oh Ok, Thanks a lot for the response.
