### ISSUE TITLE
Can not get Credentials from AWS ECS

### ISSUE THREAD

**Issue by crazygit** [guardian/kinesis-logback-appender#14]
When deploy to ecs, I found it can not get credentials from ecs task role.
Maybe need add [ContainerCredentialsProvider](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/auth/ContainerCredentialsProvider.html) in [CustomCredentialsProviderChain.java](https://github.com/guardian/kinesis-logback-appender/blob/master/src/main/java/com/gu/logback/appender/kinesis/helpers/CustomCredentialsProviderChain.java)

**Comment by mbarton** [comment]
Hi @crazygit thanks for reporting. I think it could make sense to add that provider to the chain but in the meantime you can create a new Kinesis Appender with the credentials provider you need and add it in.

Here's an example (using a Logstash layout but you could use any sort):

```java
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.spi.ILoggingEvent;
import com.gu.logback.appender.kinesis.KinesisAppender;
import net.logstash.logback.layout.LogstashLayout;
import org.slf4j.LoggerFactory;
import com.amazonaws..auth.ContainerCredentialsProvider;

public class LoggerSwap {
    public static void swapLogger() {
        Logger rootLogger = (Logger) LoggerFactory.getLogger(org.slf4j.Logger.ROOT_LOGGER_NAME);

        LogstashLayout layout = new LogstashLayout();
        layout.setContext(rootLogger.getLoggerContext());
        layout.start();

        KinesisAppender<ILoggingEvent> appender = new KinesisAppender<>();
        appender.setBufferSize(1000);
        appender.setRegion("eu-west-1");
        appender.setStreamName("KINESIS_STREAM_NAME");
        appender.setContext(rootLogger.getLoggerContext());
        appender.setLayout(layout);
        appender.setCredentialsProvider(new ContainerCredentialsProvider());
        appender.start();

        // Stop the existing one if you have configured it
        rootLogger.getAppender("console").stop();
        rootLogger.addAppender(appender);
    }
}
```

**Comment by crazygit** [comment]
@mbarton 
Thanks!

**Comment by x-cray** [comment]
Unfortunately changes from #27 have been reverted by #29
