### ISSUE TITLE
Support for Kinesis Firehose

### ISSUE THREAD

**Issue by andrewdmay** [guardian/kinesis-logback-appender#7]
I'm currently working on a fork of this project to add Kinesis Firehose support after I discovered I couldn't use a Kinesis appender for Firehose due to differences in the AWS APIs.

Let me know if this is something you'd accept as a contribution and I can put in a pull request once I'm done. 

Regards,
Andrew

**Comment by kenoir** [comment]
We'd definitely accept it as a contribution, if you're happy to submit the PR still.

**Comment by andrewdmay** [comment]
See pull request #8 . Let me know if there are any changes you'd like me to make.
We've been using my fork with Firehose for the last few months without any issues. I haven't tested it with regular Kinesis.
