### ISSUE TITLE
Where are you publishing the jar?

### ISSUE THREAD

**Issue by toadkicker** [guardian/kinesis-logback-appender#9]
I looked in your pom and see you're pointing here: https://oss.sonatype.org/content/repositories/snapshots/com/gu/

but I don't see this in the directory? How would I reference this in maven?

**Comment by kenoir** [comment]
I don't do much pure Java development (we're consuming this from Scala apps where we use it), so i'm not sure exactly how to do this. Does this help: http://stackoverflow.com/questions/13945757/how-do-you-import-a-maven-dependency-from-sonatype-org ?

**Comment by mchv** [comment]
@toadkicker not in `snapshots` but in [`releases`](https://oss.sonatype.org/content/repositories/releases/com/gu/)
